stages:
  - build
  - deploy

.libjpeg:
  before_script:
    - curl http://www.ijg.org/files/jpegsrc.v9d.tar.gz > jpegsrc.tar.gz
    - tar xvf jpegsrc.tar.gz
    - cd jpeg-9d
    - ./configure --enable-static --with-pic
    - make install
    - cd ..

.wheel:
  image: quay.io/pypa/manylinux2014_x86_64
  extends: .libjpeg
  stage: build
  variables: 
    PYBIN: /opt/python/$PYVER/bin
  script:
    - yum install util-linux
    - ${PYBIN}/pip install -r dev-requirements.txt
    - ${PYBIN}/pip wheel . --no-deps -w dist/
    - rename linux manylinux2014 dist/*
  artifacts:
    paths:
      - dist/*
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  
wheel-36:
  extends: .wheel
  variables: 
    PYVER: cp36-cp36m
    
wheel-37:
  extends: .wheel
  variables: 
    PYVER: cp37-cp37m

wheel-38:
  extends: .wheel
  variables: 
    PYVER: cp38-cp38

pypi:
  stage: deploy
  image: python
  script:
    - pip install twine
    - twine upload -u __token__ -p ${pypi_push_key} dist/*
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_BRANCH == master'
      when: on_success

pages:
  stage: deploy
  image: python:3.8
  script:
    - wheel_38=`ls dist/*38*`
    - pip install ${wheel_38}
    - cd doc
    - pip install -r requirements.txt
    - make html
    - mv build ../public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_BRANCH == master'
      when: on_success